apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"labels":{"app":"nextcloud"},"name":"nextcloud-pvc","namespace":"default"},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"5Gi"}},"selector":{"matchLabels":null}}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2021-11-30T12:51:51Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: nextcloud
  name: nextcloud-pvc
  namespace: default
  resourceVersion: "28386761"
  uid: 7c3ebaee-e0ee-4e4c-bda9-f0ad13aa9c38
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector: {}
  volumeMode: Filesystem
  volumeName: nextcloud-pv
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  phase: Bound
