network:
  version: 2
  renderer: networkd

  ethernets:
    eth0:
      dhcp4: false 
      dhcp6: false 

  bridges:
    br0:
      interfaces: [eth0]
      addresses: [192.168.0.200/24]
      # gateway4 is deprecated, use routes instead
      routes:
      - to: default
        via: 192.168.0.1
        metric: 100
        on-link: true
      mtu: 1500
      nameservers:
        addresses: [192.168.0.200 8.8.8.8, 8.8.4.4]
      parameters:
        stp: true
        forward-delay: 4
      dhcp4: no
      dhcp6: no