---
# tasks file for node_exporter
- name: Create node_exporter user account
  user:
    name: node_exporter
    shell: /bin/false
    create_home: no
    state: present

- name: Download node_exporter installer package for arm64
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-arm64.tar.gz"
    dest: /tmp
  when: ansible_architecture == 'aarch64'

- name: Download node_exporter installer package for x86_64
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp
  when: ansible_architecture == 'x86_64'

- name: Extract the installer package
  unarchive:
    src: "{{ (ansible_architecture == 'aarch64') | ternary(installer_arm_src, installer_x86_src) }}.tar.gz"
    remote_src: yes
    dest: /tmp

- name: Copy node_exporter binary
  copy:
    src: "{{ (ansible_architecture == 'aarch64') | ternary(installer_arm_src, installer_x86_src) }}/node_exporter"
    dest: /usr/local/bin
    owner: node_exporter
    group: node_exporter
    remote_src: yes
    mode: '0755'

- name: Create node_exporter systemd service
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0755'

- name: Start and enable node_exporter systemd service
  systemd:
    name: node_exporter.service
    state: started
    enabled: yes
    daemon_reload: yes
