---
- name: create infra group
  group:
    name: infra
    gid: 5000

- name: create infra user
  user:
    name: infra1
    comment: "Infra user ID"
    group: infra
    uid: 5001
    shell: /bin/bash

- name: setup authorized_keys for infra1 user
  authorized_key:
    user: infra1
    state: present
    key: "{{ lookup('file', 'id_rsa.infra1.pub') }}"

- name: create monet group
  group:
    name: monet
    gid: 8000

- name: create monet user
  user:
    name: monet
    comment: "Developer ID - monet"
    group: monet
    uid: 8001
    shell: /bin/bash

- name: setup authorized_keys for monet user
  authorized_key:
    user: monet
    state: present
    key: "{{ lookup('file', 'id_rsa.monet.pub') }}"

- debug: msg="{{ ansible_date_time.tz }}"

- block:
    - name: remove existing /etc/localtime
      file:
        path: /etc/localtime
        state: absent

    - name: Set timezone to SGT
      timezone: 
        name: Asia/Singapore
  when: ansible_date_time.tz != '+08'

- name: create custom sudo
  template:
    src: sudo.j2
    dest: /etc/sudoers.d/home-admin-users
    mode: '0440'
    owner: root
    group: root

- name: fix infra1 homedir ownership for lxc guests
  file:
    path: /home/infra1
    owner: infra1
    group: infra
    state: directory
    recurse: true
  when: ansible_virtualization_type == 'lxc'

