---
# tasks file for postbuild
- name: set hostname
  command: hostnamectl set-hostname "{{ hostname }}"

- name: set static ip address
  template:
    src: ip_entries.j2
    dest: /etc/netplan/50-cloud-init.yaml
  notify: netplan apply

- name: remove ubuntu user
  user:
    name: ubuntu
    state: absent
    remove: yes
