---
- name: add sudo for raemone user
  lineinfile:
    path: /etc/sudoers.d/90-cloud-init-users
    line: 'raemone        ALL=(ALL)       NOPASSWD: ALL'

- name: add sudo for sabuser user
  lineinfile:
    path: /etc/sudoers.d/90-cloud-init-users
    line: 'sabuser        ALL=(ALL)       NOPASSWD: ALL'

- name: install base packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - net-tools
    - docker.io
    - nfs-common
    - unzip

- name: add raemone user to docker group
  user:
    name: raemone
    groups: docker
    append: yes

- name: set hostname
  command: hostnamectl set-hostname "{{ hostname }}"

- name: set static ip address
  template:
    src: ip_entries.j2
    dest: /etc/netplan/50-cloud-init.yaml
  notify: netplan apply

- name: set cgroups docker driver
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root

- name: enable cgroups limit support
  command: sed -i '$ s/$/ cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 swapaccount=1/' /boot/firmware/cmdline.txt

