galaxy_info:
  author: Ramon
  description: RPI OS Customization
  company: homelab
  role_name: pi_basebuild
  namespace: homelab
  license: MIT
  min_ansible_version: 2.1
  platforms:
   - name: Ubuntu
     versions:
     - focal
   - name: centos
     versions:
     - 7
     - 8
  galaxy_tags: []
dependencies: []
